library IEEE;
use IEEE.std_logic_1164.all;

ENTITY CLK_10KHZ IS
PORT(
	H_2_5_MHZ : IN STD_LOGIC;
	H_10KHZ : OUT STD_LOGIC
	);
END CLK_10KHZ ;

ARCHITECTURE archi OF CLK_10KHZ IS
	SIGNAL CPT : INTEGER RANGE 0 TO 250;
BEGIN
	PROCESS(H_2_5_MHZ)
	BEGIN
		IF(H_2_5_MHZ'EVENT AND H_2_5_MHZ='1') THEn
			IF CPT = 249 THEN 
				CPT <= 0;
				H_10KHZ <= '1';
			ELSE
				CPT <= CPT + 1;
				H_10KHZ <= '0';
			END IF;
		END IF;
	END PROCESS;
END archi;
